export const ADD_QUESTION = "ADD_QUESTION"
export const CREATE_QUIZ = "CREATE_QUIZ"
export const INCREASE_RIGHT_ANSWER = "INCREASE_RIGHT_ANSWER"

export const UPDATED_LIST = "UPDATED_LIST"
export const UPDATE_QUIZZES = "UPDATE_QUIZZES"
export const NO_TESTS = 'NO_TESTS'
export const LIST_RESET = 'LIST_RESET'

export const QUESTION_SWITCH = "QUESTION_SWITCH"
export const CHANGE_QUESTION_STATE = "CHANGE_QUESTION_STATE"
export const FINISHED_QUIZ = "FINISHED_QUIZ"
export const CHANGE_PROPERTY = "CHANGE_PROPERTY"

export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const LOGOUT = "LOGOUT"
export const CHANGED_ERROR = "CHANGED_ERROR"
export const AUTH_ERROR = "AUTH_ERROR"
